# Generated by Django 5.0.7 on 2024-11-08 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('pedidos', '0003_pedido_status_alter_pedido_nome_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
    ]
