# Generated by Django 5.0.7 on 2024-10-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
