# Generated by Django 5.1.1 on 2024-10-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_quantidade_produto_formula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='formula',
        ),
    ]
