# Generated by Django 5.1.1 on 2024-09-25 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
        ),
    ]
