# Generated by Django 5.1.1 on 2024-10-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0003_alter_produto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cod', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('produto', models.ManyToManyField(to='produtos.produto')),
            ],
        ),
    ]
