# Generated by Django 5.1.1 on 2024-10-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('Revenda', 'Revenda'), ('Produtor', 'Produtor'), ('Usina', 'Usina'), ('Cooperativa', 'cooperativa')], max_length=20),
        ),
    ]
