# Generated by Django 5.1.5 on 2025-01-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('Revenda', 'Revenda'), ('Produtor', 'Produtor'), ('Usina', 'Usina'), ('Cooperativa', 'Cooperativa'), ('Granuladora', 'Granuladora')], max_length=20)),
            ],
        ),
    ]
